# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springdatarest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdatarest
  template:
    metadata:
      labels:
        app: springdatarest
    spec:
      containers:
      - name: springdatarest-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/cloudy-hr-001/springdatarest:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
